name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./supply-chain-information-managed/pom.xml
          mvn clean package -f ./inventory-monitored/pom.xml
          mvn clean package -f ./production-plan-managed/pom.xml
          mvn clean package -f ./order-created/pom.xml
          mvn clean package -f ./customer-verified-and-contacted/pom.xml
          mvn clean package -f ./fish-dispatched-and-delivered/pom.xml
          mvn clean package -f ./order-history-checked/pom.xml
          mvn clean package -f ./inventory-checked/pom.xml
          mvn clean package -f ./inventory-adjusted/pom.xml
          mvn clean package -f ./expiration-date-managed/pom.xml

      - name: Docker Build and push for SupplyChainInformationManaged
        uses: docker/build-push-action@v4
        with:
          context: ./supply-chain-information-managed
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/supply-chain-information-managed:latest
            ghcr.io/${{ github.repository }}/supply-chain-information-managed:${{ github.ref_name }}
            
      - name: Docker Build and push for InventoryMonitored
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-monitored
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/inventory-monitored:latest
            ghcr.io/${{ github.repository }}/inventory-monitored:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductionPlanManaged
        uses: docker/build-push-action@v4
        with:
          context: ./production-plan-managed
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/production-plan-managed:latest
            ghcr.io/${{ github.repository }}/production-plan-managed:${{ github.ref_name }}
            
      - name: Docker Build and push for OrderCreated
        uses: docker/build-push-action@v4
        with:
          context: ./order-created
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order-created:latest
            ghcr.io/${{ github.repository }}/order-created:${{ github.ref_name }}
            
      - name: Docker Build and push for CustomerVerifiedAndContacted
        uses: docker/build-push-action@v4
        with:
          context: ./customer-verified-and-contacted
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-verified-and-contacted:latest
            ghcr.io/${{ github.repository }}/customer-verified-and-contacted:${{ github.ref_name }}
            
      - name: Docker Build and push for FishDispatchedAndDelivered
        uses: docker/build-push-action@v4
        with:
          context: ./fish-dispatched-and-delivered
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fish-dispatched-and-delivered:latest
            ghcr.io/${{ github.repository }}/fish-dispatched-and-delivered:${{ github.ref_name }}
            
      - name: Docker Build and push for OrderHistoryChecked
        uses: docker/build-push-action@v4
        with:
          context: ./order-history-checked
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order-history-checked:latest
            ghcr.io/${{ github.repository }}/order-history-checked:${{ github.ref_name }}
            
      - name: Docker Build and push for InventoryChecked
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-checked
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/inventory-checked:latest
            ghcr.io/${{ github.repository }}/inventory-checked:${{ github.ref_name }}
            
      - name: Docker Build and push for InventoryAdjusted
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-adjusted
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/inventory-adjusted:latest
            ghcr.io/${{ github.repository }}/inventory-adjusted:${{ github.ref_name }}
            
      - name: Docker Build and push for ExpirationDateManaged
        uses: docker/build-push-action@v4
        with:
          context: ./expiration-date-managed
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/expiration-date-managed:latest
            ghcr.io/${{ github.repository }}/expiration-date-managed:${{ github.ref_name }}
            
