apiVersion: v1
kind: Service
metadata:
  name: fish-dispatched-and-delivered
  labels:
    app: fish-dispatched-and-delivered
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fish-dispatched-and-delivered