apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-plan-managed
  labels:
    app: production-plan-managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-plan-managed
  template:
    metadata:
      labels:
        app: production-plan-managed
    spec:
      containers:
        - name: production-plan-managed
          image: "username/production-plan-managed:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
