apiVersion: v1
kind: Service
metadata:
  name: production-plan-managed
  labels:
    app: production-plan-managed
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: production-plan-managed