apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-checked
  labels:
    app: order-history-checked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-history-checked
  template:
    metadata:
      labels:
        app: order-history-checked
    spec:
      containers:
        - name: order-history-checked
          image: "username/order-history-checked:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
