apiVersion: v1
kind: Service
metadata:
  name: order-history-checked
  labels:
    app: order-history-checked
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-history-checked