apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-verified-and-contacted
  labels:
    app: customer-verified-and-contacted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-verified-and-contacted
  template:
    metadata:
      labels:
        app: customer-verified-and-contacted
    spec:
      containers:
        - name: customer-verified-and-contacted
          image: "username/customer-verified-and-contacted:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
