apiVersion: v1
kind: Service
metadata:
  name: customer-verified-and-contacted
  labels:
    app: customer-verified-and-contacted
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-verified-and-contacted