apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-monitored
  labels:
    app: inventory-monitored
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-monitored
  template:
    metadata:
      labels:
        app: inventory-monitored
    spec:
      containers:
        - name: inventory-monitored
          image: "username/inventory-monitored:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
