apiVersion: v1
kind: Service
metadata:
  name: inventory-monitored
  labels:
    app: inventory-monitored
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-monitored