---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-information-managed
  labels:
    app: supply-chain-information-managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-chain-information-managed
  template:
    metadata:
      labels:
        app: supply-chain-information-managed
    spec:
      containers:
        - name: supply-chain-information-managed
          image: username/supply-chain-information-managed:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-monitored
  labels:
    app: inventory-monitored
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-monitored
  template:
    metadata:
      labels:
        app: inventory-monitored
    spec:
      containers:
        - name: inventory-monitored
          image: username/inventory-monitored:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-plan-managed
  labels:
    app: production-plan-managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-plan-managed
  template:
    metadata:
      labels:
        app: production-plan-managed
    spec:
      containers:
        - name: production-plan-managed
          image: username/production-plan-managed:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-created
  labels:
    app: order-created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-created
  template:
    metadata:
      labels:
        app: order-created
    spec:
      containers:
        - name: order-created
          image: username/order-created:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-verified-and-contacted
  labels:
    app: customer-verified-and-contacted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-verified-and-contacted
  template:
    metadata:
      labels:
        app: customer-verified-and-contacted
    spec:
      containers:
        - name: customer-verified-and-contacted
          image: username/customer-verified-and-contacted:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fish-dispatched-and-delivered
  labels:
    app: fish-dispatched-and-delivered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fish-dispatched-and-delivered
  template:
    metadata:
      labels:
        app: fish-dispatched-and-delivered
    spec:
      containers:
        - name: fish-dispatched-and-delivered
          image: username/fish-dispatched-and-delivered:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-checked
  labels:
    app: order-history-checked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-history-checked
  template:
    metadata:
      labels:
        app: order-history-checked
    spec:
      containers:
        - name: order-history-checked
          image: username/order-history-checked:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-checked
  labels:
    app: inventory-checked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-checked
  template:
    metadata:
      labels:
        app: inventory-checked
    spec:
      containers:
        - name: inventory-checked
          image: username/inventory-checked:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-adjusted
  labels:
    app: inventory-adjusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-adjusted
  template:
    metadata:
      labels:
        app: inventory-adjusted
    spec:
      containers:
        - name: inventory-adjusted
          image: username/inventory-adjusted:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-date-managed
  labels:
    app: expiration-date-managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-date-managed
  template:
    metadata:
      labels:
        app: expiration-date-managed
    spec:
      containers:
        - name: expiration-date-managed
          image: username/expiration-date-managed:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: supply-chain-information-managed
  labels:
    app: supply-chain-information-managed
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: supply-chain-information-managed


---


apiVersion: v1
kind: Service
metadata:
  name: inventory-monitored
  labels:
    app: inventory-monitored
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-monitored


---


apiVersion: v1
kind: Service
metadata:
  name: production-plan-managed
  labels:
    app: production-plan-managed
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: production-plan-managed


---


apiVersion: v1
kind: Service
metadata:
  name: order-created
  labels:
    app: order-created
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-created


---


apiVersion: v1
kind: Service
metadata:
  name: customer-verified-and-contacted
  labels:
    app: customer-verified-and-contacted
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-verified-and-contacted


---


apiVersion: v1
kind: Service
metadata:
  name: fish-dispatched-and-delivered
  labels:
    app: fish-dispatched-and-delivered
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fish-dispatched-and-delivered


---


apiVersion: v1
kind: Service
metadata:
  name: order-history-checked
  labels:
    app: order-history-checked
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-history-checked


---


apiVersion: v1
kind: Service
metadata:
  name: inventory-checked
  labels:
    app: inventory-checked
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-checked


---


apiVersion: v1
kind: Service
metadata:
  name: inventory-adjusted
  labels:
    app: inventory-adjusted
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-adjusted


---


apiVersion: v1
kind: Service
metadata:
  name: expiration-date-managed
  labels:
    app: expiration-date-managed
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: expiration-date-managed

