apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-adjusted
  labels:
    app: inventory-adjusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-adjusted
  template:
    metadata:
      labels:
        app: inventory-adjusted
    spec:
      containers:
        - name: inventory-adjusted
          image: "username/inventory-adjusted:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
